In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv')

In [6]:
df.sample(5)

age  gender   review education purchased
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
0    30  Female  Average    School        No
17   22  Female     Poor        UG       Yes
45   61    Male     Poor        PG       Yes

### gender is nominal
### review and education is ordinal
### purchased is Label

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()
# now we need to use ordinal and label encoder

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
# always do train test split before feature transformation

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [12]:
X_train.shape,X_test.shape

((40, 2), (10, 2))

In [13]:
from sklearn.preprocessing import OrdinalEncoder


In [14]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
oe.fit(X_train)
# first fitting train data to learn parameters

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [19]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [21]:
X_train,X_test

(array([[1., 1.],
        [0., 1.],
        [0., 2.],
        [1., 0.],
        [0., 0.],
        [2., 0.],
        [0., 0.],
        [0., 0.],
        [0., 2.],
        [0., 1.],
        [1., 1.],
        [2., 2.],
        [2., 1.],
        [2., 2.],
        [1., 2.],
        [2., 0.],
        [2., 1.],
        [0., 2.],
        [1., 1.],
        [2., 2.],
        [1., 0.],
        [0., 2.],
        [2., 2.],
        [2., 1.],
        [0., 2.],
        [2., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.],
        [0., 2.],
        [0., 2.],
        [0., 2.],
        [2., 2.],
        [1., 1.],
        [2., 1.],
        [2., 0.],
        [2., 0.],
        [1., 0.]]),
 array([[2., 2.],
        [1., 2.],
        [2., 1.],
        [1., 2.],
        [2., 0.],
        [0., 0.],
        [0., 2.],
        [0., 1.],
        [2., 1.],
        [1., 1.]]))

In [22]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [23]:
from sklearn.preprocessing import LabelEncoder
# use label encoder only for target values i.e y not X

In [24]:
le = LabelEncoder()

In [26]:
le.fit(y_train)

LabelEncoder()

In [27]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [28]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [29]:
y_train , y_test

(array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0]))